import pandas as pd
import os

def run_verification():
    """
    Strict correctness audit: compares final pipeline output (Pass 1 + Pass 2 + Pass 3)
    against the hidden ground-truth pairings generated by generate_data.py.

    Confusion-matrix definitions (row-level, one row per ground-truth transaction):
      TP - txn had a true match AND we predicted the correct ledger_id
      FP - we predicted a ledger_id but it was wrong (includes predicting a match
           for a txn that has no true match at all, i.e. true_ledger_id is null)
      FN - txn had a true match but we predicted nothing (ledger_id is null)

    Note: a wrong prediction is counted as FP only, never double-counted as FN too.
    This mirrors sklearn's precision/recall semantics for a matching task.
    """
    if not os.path.exists("ground_truth.csv"):
        print("Run generate_data.py first to create ground_truth.csv")
        return

    gt_df = pd.read_csv("ground_truth.csv")

    m1 = pd.read_csv("matches_stage1.csv") if os.path.exists("matches_stage1.csv") else pd.DataFrame()
    m2 = pd.read_csv("matches_stage2.csv") if os.path.exists("matches_stage2.csv") else pd.DataFrame()

    # Staleness guard: matches_stage2.csv only makes sense alongside a
    # matches_stage1.csv from the SAME run. If stage1 is missing/older than
    # stage2, or the txn_ids don't fit within ground_truth at all, warn rather
    # than silently reporting numbers computed against mismatched files.
    if not m1.empty and os.path.exists("matches_stage1.csv") and os.path.exists("matches_stage2.csv"):
        if os.path.getmtime("matches_stage1.csv") > os.path.getmtime("matches_stage2.csv"):
            print("⚠️  WARNING: matches_stage1.csv is newer than matches_stage2.csv — "
                  "did Pass 3 (pass3_engine.py) finish running after the latest Pass 1/2 run? "
                  "Numbers below may reflect a stale AI pass.\n")

    all_matches = pd.concat([m1, m2], ignore_index=True) if not m1.empty or not m2.empty else pd.DataFrame(columns=['txn_id', 'ledger_id'])

    # Sanity check: the pipeline should never assign the same ledger_id to two
    # different bank transactions. Flag it loudly if it ever happens instead of
    # letting it silently corrupt the precision/recall numbers below.
    if not all_matches.empty:
        dup_ledger_ids = all_matches[all_matches['ledger_id'].notna() & all_matches.duplicated(subset=['ledger_id'], keep=False)]
        if not dup_ledger_ids.empty:
            print("⚠️  WARNING: The same ledger_id was matched to multiple txn_ids — this should be impossible:")
            print(dup_ledger_ids.sort_values('ledger_id').to_string(index=False))
            print()

    # Merge truth with predicted matches (left join keeps every ground-truth row exactly once)
    eval_df = pd.merge(gt_df, all_matches[['txn_id', 'ledger_id']], on='txn_id', how='left')

    predicted = eval_df['ledger_id'].notna()
    has_true_match = eval_df['true_ledger_id'].notna()
    correct = eval_df['ledger_id'] == eval_df['true_ledger_id']

    tp = len(eval_df[predicted & has_true_match & correct])
    fp = len(eval_df[predicted & ~correct])            # wrong ledger_id, OR matched a txn that had no true match
    fn = len(eval_df[~predicted & has_true_match])      # should have matched, but we predicted nothing

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = (2 * precision * recall / (precision + recall)) if (precision + recall) > 0 else 0.0

    print("\n--- PIPELINE ACCURACY AUDIT ---")
    print(f"Total Ground-Truth Rows: {len(eval_df)}")
    print(f"True Positives (TP):  {tp}")
    print(f"False Positives (FP): {fp}")
    print(f"False Negatives (FN): {fn}")
    print(f"Precision Score:      {precision:.2%}")
    print(f"Recall Score:         {recall:.2%}")
    print(f"F1 Score:             {f1:.2%}\n")

if __name__ == "__main__":
    run_verification()